BankAspNetCore/Controllers/CompteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BankAspNetCore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BankAspNetCore.Controllers
{
    public class CompteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Policy = "admin")]
        public IActionResult Search(int numero)
        {
            return View("Index", Compte.GetCompteById(numero));
        }

        [Authorize(Policy = "admin")]
        [HttpGet]
        public IActionResult CreationCompte(string message,string type)
        {
            if(message != null && type != null)
            {
                ViewBag.Message = message;
                ViewBag.Type = type;
            }
            return View("FormCompte");
        }

        [Authorize(Policy = "admin")]
        [HttpPost]
        public IActionResult SubmitCreationCompte(Client client, decimal solde)
        {
            Compte compte = new Compte(client, solde);
            string message = "";
            string type = "";
            if(compte.Save())
            {
                type = "success";
                message = "Compte créé avec le numéro " + compte.Numero; 
            }
            else
            {
                type = "danger";
                message = "Erreur de création de compte";
            }
            return RedirectToAction("CreationCompte", new { message = message, type = type });
        }

        [Authorize(Policy = "superAdmin")]

        public IActionResult Operation(int id, string type)
        {
            ViewBag.Type = type;
            ViewBag.Numero = id;
            return View();
        }

        [Authorize(Policy = "superAdmin")]

        public IActionResult SubmitOperation(int numero, decimal montant, string type)
        {
            Compte compte = Compte.GetCompteById(numero);
            if(compte != null)
            {
                if(type == "depot")
                {
                    compte.Depot(montant);
                }
                else if(type == "retrait")
                {
                    compte.Retrait(montant);
                }
                return RedirectToAction("Search", new { numero = compte.Numero });
            }
            
            return RedirectToAction("Index");
        }
    }
}

BankAspNetCore/Views/Shared/_Layout.cshtml
@inject ILogin _login
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BankAspNetCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Compte" asp-action="Index">BankAspNetCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Compte" asp-action="Index">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Compte" asp-action="CreationCompte">Création Compte</a>
                        </li>
                        @if (_login.GetName() != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="LogOut">Se deconnecter</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark">@_login.GetName()</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BankAspNetCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>