fakeboncoin/Controllers/AnnonceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using fakeboncoin.Models;
using fakeboncoin.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace fakeboncoin.Controllers
{
    public class AnnonceController : Controller
    {
        private IWebHostEnvironment _env;

        private IFavoris _favorisService;

        private IUpload _uploadService;

        private ILogin _login;

        public AnnonceController(IWebHostEnvironment env, IFavoris favoris, IUpload uploadService, ILogin login)
        {
            _env = env;
            _favorisService = favoris;
            _uploadService = uploadService;
            _login = login;
        }

        [Authorize(Policy = "connect")]
        public IActionResult Index(string search)
        {
            //ViewBag.Email = _login.GetEmail();
            List<Annonce> annonces = null;
            if (search != null)
                annonces = Annonce.Search(search);
            return View(annonces);
        }

        public IActionResult DetailAnnonce(int id)
        {
            ViewBag.BaseUrl = "https://localhost:44301/";
            //List<Annonce> annonces = GetAnnoncesFromSessionOrCookies();
            //List<Annonce> annonces = _favorisService.GetFavoris();
            ViewBag.isFavoris = _favorisService.IsFavoris(id);
            return View(Annonce.GetAnnonce(id));
        }


        [Authorize(Policy = "connectAdmin")]
        public IActionResult FormAnnonce()
        {
            //if (!_login.IsLogged())
            //{
            //    return RedirectToAction("Login", "Authentication");
            //}
            return View();
        }

        [HttpPost]
        public IActionResult SubmitFromAnnonce(Annonce annonce, IFormFile[] images)
        {
            foreach(IFormFile image in images)
            {
                annonce.Images.Add(new Image() { Url = _uploadService.Upload(image) });
            }
            annonce.Save();
            return RedirectToAction("Index");
        }

        //private string Upload(IFormFile file)
        //{
        //    string pathFile = Path.Combine(_env.WebRootPath, "images", file.FileName);
        //    Stream stream = System.IO.File.Create(pathFile);
        //    file.CopyTo(stream);
        //    stream.Close();
        //    return "images/" + file.FileName;
        //}


        public IActionResult Favoris()
        {
            //string annoncesString = HttpContext.Session.GetString("annonces");
            //List<Annonce> annonces = (annoncesString != null)
            //        ? JsonConvert.DeserializeObject<List<Annonce>>(annoncesString)
            //        : new List<Annonce>();
            //return View(GetAnnoncesFromSessionOrCookies());
            return View(_favorisService.GetFavoris());
        }

        public IActionResult AddToFavoris(int id)
        {
            //Annonce a = Annonce.GetAnnonce(id);
            //if (a != null)
            //{
            //    List<Annonce> annonces = GetAnnoncesFromSessionOrCookies();
            //    annonces.Add(a);
            //    //HttpContext.Session.SetString("annonces", JsonConvert.SerializeObject(annonces));
            //    HttpContext.Response.Cookies.Append("annonces", JsonConvert.SerializeObject(annonces));
            //}

            _favorisService.AddToFavoris(id);
            return RedirectToAction("Favoris");
        }


        public IActionResult RemoveFromFavoris(int id)
        {
            //List<Annonce> annonces = GetAnnoncesFromSessionOrCookies();
            //Annonce annonce = annonces.Find(a => a.Id == id);
            //if(annonce != null)
            //{
            //    annonces.Remove(annonce);
            //    //HttpContext.Session.SetString("annonces", JsonConvert.SerializeObject(annonces));
            //    HttpContext.Response.Cookies.Append("annonces", JsonConvert.SerializeObject(annonces));
            //}
            _favorisService.RemoveFromFavoris(id);
            return RedirectToAction("Favoris");
        }

        //private List<Annonce> GetAnnoncesFromSessionOrCookies()
        //{
        //    //string annoncesString = HttpContext.Session.GetString("annonces");
        //    string annoncesString = HttpContext.Request.Cookies["annonces"];
        //    List<Annonce> annonces = (annoncesString != null)
        //        ? JsonConvert.DeserializeObject<List<Annonce>>(annoncesString)
        //        : new List<Annonce>();

        //    return annonces;
        //}
        public IActionResult GetUrl()
        {
            return View();
        }
    }
}

fakeboncoin/Views/Shared/_Layout.cshtml
@inject ILogin _login
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - fakeboncoin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Annonce" asp-action="Index">fakeboncoin</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Annonce" asp-action="Index">Rechercher annonce</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Annonce" asp-action="FormAnnonce">Ajouter une annonce</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Annonce" asp-action="Favoris">Favoris</a>
                        </li>
                        @if (_login.GetEmail() != null)
                        {
                            <li class="nav-item">
                                @_login.GetEmail()
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="LogOut">se deconnecter</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - fakeboncoin
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>